service: stock-api

useDotenv: true

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    API_TOKEN: ${env:API_TOKEN}
    API_URL: ${env:API_URL}
    STAGE: lambda

package:
  individually: true
  exclude:
    - stock-ui/**
    - node_modules/**
    - .git/**
    - .gitignore
    - Dockerfile
    - docker-compose.yml

functions:
  stock-api:
    handler: bootstrap
    runtime: provided.al2
    package:
      artifact: function-stocks.zip
    events:
      - http:
          path: /api/stocks
          method: get

  recommendation-api:
    handler: bootstrap
    runtime: provided.al2
    package:
      artifact: function-recommendations.zip
    events:
      - http:
          path: /api/recommendations
          method: get
